### ISSUE TITLE
Why is gitlens mandatory?

### ISSUE THREAD

**Issue by Lawouach** [harishekhar/vuejs-workbox#1]
Hey,

Sorry for the perhaps daft question. I really enjoy this extension but I find GitLens irritating, it seems I cannot remove it because your extension requires it. Is that mandatory?

Cheers,

**Comment by shekhardtu** [comment]
Hi @Lawouach, 
If you don't need gitlens features, and want all gitlens features to be turn off. 
Paste these commands in your settings file.

`
"gitlens.codeLens.enabled": false,
"gitlens.currentLine.enabled": false,
"gitlens.statusBar.enabled": false,
`

Cheers!

**Comment by Lawouach** [comment]
Oooh nice! Thank you for making the time finding the right settings there.
